// <auto-generated />
using System;
using Forum.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Forum.Migrations
{
    [DbContext(typeof(PostingDBContext))]
    [Migration("20181130035243_Initialmessage")]
    partial class Initialmessage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Forum.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FloorId");

                    b.Property<DateTime>("MessageTime");

                    b.Property<string>("Messager");

                    b.Property<string>("Text");

                    b.Property<int>("TopicId");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Forum.Models.Posting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("Poster");

                    b.Property<DateTime>("Posttime");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Postings");
                });
#pragma warning restore 612, 618
        }
    }
}
